# Generated by Django 4.1.1 on 2022-10-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='breaf_desc',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.AddField(
            model_name='destination',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='small_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
