# Generated by Django 4.1.1 on 2022-10-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_desc_destination_breaf_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='place_code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
