# Generated by Django 4.1.1 on 2022-10-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_destination_place_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tab_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
