# Generated by Django 4.1.1 on 2022-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_destination_tab_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_code', models.CharField(max_length=3)),
                ('booking_owner', models.CharField(max_length=40)),
                ('persons_name', models.TextField()),
                ('slot', models.CharField(max_length=40)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
