# Generated by Django 4.1.1 on 2022-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
