# Generated by Django 4.1.1 on 2022-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='count',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
