# Generated by Django 4.1.1 on 2022-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_booking_persons_adhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='count',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
