# Generated by Django 3.0.14 on 2022-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20221106_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='persons_age',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='persons_gender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
